apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysecretdb
  name: mysecretdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysecretdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysecretdb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        resources: {}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mydbpw
status: {}
